application: galacticcourier
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
- url: /css
  static_dir: css

- url: /flight_test
  static_dir: flight_test
  
- url: /packages
  static_dir: packages
  
- url: /maps
  static_dir: maps
  
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest
  
- name: numpy
  version: latest