application: galacticcourier
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
- url: /css
  static_dir: css

- url: /main
  static_dir: src/main
  
- url: /thirdpartylibraries
  static_dir: src/thirdpartylibraries
  
- url: /setup
  static_dir: src/setup
  
- url: /maps
  static_dir: src/maps
  
- url: /classes
  static_dir: src/classes
  
  
- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest
  
- name: numpy
  version: latest